### ISSUE TITLE
Investigate options to block azure storage account when limits are reached

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#266]
Requirement described in https://github.com/ssc-sp/datahub-docs/blob/main/Platform/Azure/Storage_Limits.md

**Comment by simon-wang-gc** [comment]
Theoratically feasible options but NOT tested

- Soft delete CMK or disable CMK access in Key Vault, which should render storage inaccessible
- Disable Access Key
- Disable public network access

**Comment by simon-wang-gc** [comment]
The best approach is believed to DISABLE the CMK for the project. Unlike deleting the key, there is no time limit when the key is brought back. In the case of key deletion, the key can be purged automatically after the purge period (e.g. 3 months).

Once the key is disabled, the data download or upload would result in the following message:

<Error>
<Code>KeyVaultEncryptionKeyNotFound</Code>
<Message>The key vault key is not found to unwrap the encryption key. RequestId:861e4b42-b01e-0001-44b0-29956d000000 Time:2023-01-16T13:41:34.4442045Z</Message>
</Error>

**Comment by simon-wang-gc** [comment]
When the CMK is disabled, Databricks cluster would fail to start with the following message:


Instance ID: 54f414c68ebd4fafbc7c8a5ef7c24705

Error message: Failed to launch HostedContainer{hostPrivateIP=10.139.0.4, containerIp=10.139.64.4, clusterId=0126-034040-skflbph7, resources=InstantiatedResources{memoryMB=9106, ECUs=3.0, cgroupShares=3072}, isSpot=false, id=efdf13d85b434538a6dca9ede1e25dca, instanceId=InstanceId(54f414c68ebd4fafbc7c8a5ef7c24705), state=Pending, instanceType=Standard_DS3_v2, metadata=ContainerMetadata(Standard_DS3_v2)} because starting the FUSE daemon timed out. This may happen because your VMs do not have outbound connectivity to DBFS storage. Also consider upgrading your cluster to a later spark version.

**Comment by simon-wang-gc** [comment]
The implementation will be tracked by issue #349
