### ISSUE TITLE
JS called in prerender for timezone on resources page

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#348]
![image](https://user-images.githubusercontent.com/43834308/216660160-51b5885d-c5f4-49dc-9f39-b20d24217d7c.png)

**Comment by yjmrobert** [comment]
@iroelperez I think you mentioned this was fixed in your recent PR?

**Comment by iroelperez** [comment]
@yjmrobert  I was wrong those were different problems, this issue is related to:

**JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.**

When trying to get the LocalTime using a jsInterop call in the TimeZoneService. I am looking into this right now.
