### ISSUE TITLE
Setup is missing creation of datahub admin group

### ISSUE THREAD

**Issue by ErikApption** [ssc-sp/datahub-portal#384]
The current deployment doesn't create the default group for DataHub admins. We need a way to add initial administrator(s) idreally without SQL Creds

**Comment by yjmrobert** [comment]
Maybe script this as a `portal-setup.ps1` script

**Comment by simon-wang-gc** [comment]
The design is to create the group offline and plug into the TF code. The code also assigns the group as DBA

**Comment by ErikApption** [comment]
@yjmrobert @simon-wang-gc 
DatahubProjectDBContext.cs has code to seed the database. This is used from EFTools.cs -that this is not called because the seeding only happens when the database is created by EF. Maybe we could have an environment variable to force seeding?

**Comment by yjmrobert** [comment]
I think there's value in having the database seeded but we would still need to seed the first user off their AAD OID.

I've added two sample injects that resolve this issue here:

https://github.com/ssc-sp/datahub-docs/blob/main/InstallationGuide/0001-Seed-Admin.md

How do you feel about resolving this issue for now with the scripts and creating a backlog issue to seed?

**Comment by yjmrobert** [comment]
I'm going to move this to a backlog item #475 and close it as the documentation currently explains how to get around it.
