### ISSUE TITLE
Remove DbContext from .razor files

### ISSUE THREAD

**Issue by yjmrobert** [ssc-sp/datahub-portal#623]
In order to prevent database interaction issues we should encapsulate the contexts within services and their function scopes.

This task is to identify all the uses in .razor files

**Comment by ErikApption** [comment]
I think there are benefits in having complex queries and filters inside razor files using the dbcontext directly but we should identify are  write actions because these can cause issues with multiple contexts. Also if multiple services are required then this will not solve the multiple dbcontext issue since each service is using its own dbcontext
